import React from 'react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Calendar, TrendingUp, Award, Sparkles } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, ResponsiveContainer } from 'recharts';

const ShareableReport = () => {
  // Mock data for the report
  const reportData = {
    userName: "Master Alchemist",
    currentStreak: 14,
    weeklyAverage: 95,
    totalElixirs: 3,
    adherenceData: [
      { day: 'Mon', rate: 95 },
      { day: 'Tue', rate: 100 },
      { day: 'Wed', rate: 85 },
      { day: 'Thu', rate: 100 },
      { day: 'Fri', rate: 90 },
      { day: 'Sat', rate: 100 },
      { day: 'Sun', rate: 95 },
    ]
  };

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <Card className="grimoire-header mb-8">
          <div className="flex items-center justify-center gap-4">
            <Sparkles className="h-12 w-12 text-white elixir-glow" />
            <div className="text-center">
              <h1 className="text-3xl font-bold text-white">Wellness Progress Report</h1>
              <p className="text-white/80">{reportData.userName}'s Alchemical Journey</p>
            </div>
          </div>
        </Card>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <Card className="streak-counter">
            <div className="flex items-center justify-center gap-3">
              <Award className="h-8 w-8" />
              <div>
                <p className="text-3xl font-bold">{reportData.currentStreak}</p>
                <p className="text-sm opacity-90">Day Streak</p>
              </div>
            </div>
          </Card>

          <Card className="p-6 bg-gradient-to-br from-magical-blue/20 to-magical-purple/20">
            <div className="flex items-center gap-3">
              <TrendingUp className="h-6 w-6 text-magical-blue" />
              <div>
                <p className="text-3xl font-bold text-foreground">{reportData.weeklyAverage}%</p>
                <p className="text-sm text-muted-foreground">Weekly Average</p>
              </div>
            </div>
          </Card>

          <Card className="p-6 bg-gradient-to-br from-magical-green/20 to-magical-gold/20">
            <div className="flex items-center gap-3">
              <Calendar className="h-6 w-6 text-magical-green" />
              <div>
                <p className="text-3xl font-bold text-foreground">{reportData.totalElixirs}</p>
                <p className="text-sm text-muted-foreground">Active Elixirs</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Adherence Chart */}
        <Card className="wellness-chart mb-8">
          <h2 className="text-2xl font-bold text-white mb-6">7-Day Adherence Trend</h2>
          <ResponsiveContainer width="100%" height={400}>
            <LineChart data={reportData.adherenceData}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
              <XAxis dataKey="day" stroke="white" />
              <YAxis stroke="white" />
              <Line
                type="monotone"
                dataKey="rate"
                stroke="white"
                strokeWidth={4}
                dot={{ fill: 'white', strokeWidth: 2, r: 8 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </Card>

        {/* Achievement Badges */}
        <Card className="p-8 text-center">
          <h2 className="text-2xl font-semibold text-foreground mb-6">Achievements Unlocked</h2>
          <div className="flex flex-wrap justify-center gap-4">
            <Badge className="px-4 py-2 bg-magical-purple text-white text-lg">
              🔥 Week Warrior
            </Badge>
            <Badge className="px-4 py-2 bg-magical-gold text-white text-lg">
              ⭐ Consistency Master
            </Badge>
            <Badge className="px-4 py-2 bg-magical-green text-white text-lg">
              🎯 Perfect Week
            </Badge>
          </div>

          <div className="mt-8 text-center">
            <p className="text-muted-foreground mb-4">
              This report was generated by MedKnock - Your Magical Medication Reminder
            </p>
            <p className="text-sm text-muted-foreground">
              Created on {new Date().toLocaleDateString()}
            </p>
          </div>
        </Card>
      </div>
    </div>
  );
};

export default ShareableReport;
