import fetch from "node-fetch";
import { randomUUID } from "crypto";
import Redis from "ioredis";
import dotenv from "dotenv";
dotenv.config();

// Apollo 247 uses a public (anonymous) JWT scoped to "public:read".
// It's generated by their frontend for every visitor and lasts ~12 hours.
// We cache it in Redis and fall back gracefully when expired.
//
// HOW TO REFRESH THE TOKEN (when Apollo results stop showing):
// 1. Open https://www.apollopharmacy.in in your browser
// 2. Open DevTools -> Network tab
// 3. Search for any medicine
// 4. Click any /fullSearch request -> Headers -> copy the "authorization" value
// 5. Update APOLLO_PUBLIC_TOKEN in backend/.env

const redisConfig = process.env.REDIS_URL || { host: "127.0.0.1", port: 6379, maxRetriesPerRequest: null };
const redis = new Redis(redisConfig);

const DEVICE_ID = process.env.APOLLO_DEVICE_ID || "1b7fb41e-ac52-4238-b422-5999a2d6ce35";
const CACHE_KEY = "apollo:public:token";

async function getApolloToken() {
  // 1. Check Redis cache first
  const cached = await redis.get(CACHE_KEY);
  if (cached) return cached;

  // 2. Fall back to .env token
  const envToken = process.env.APOLLO_PUBLIC_TOKEN;
  if (envToken) {
    try {
      const payload = JSON.parse(Buffer.from(envToken.split(".")[1], "base64").toString());
      const ttlSeconds = payload.exp - Math.floor(Date.now() / 1000);
      if (ttlSeconds > 60) {
        await redis.set(CACHE_KEY, envToken, "EX", ttlSeconds - 60);
        return envToken;
      }
    } catch {
      // malformed token
    }
  }

  return null;
}

export async function scrapeApollo(medicineName) {
  try {
    const token = await getApolloToken();
    if (!token) {
      console.warn("[Apollo] No valid token. Set APOLLO_PUBLIC_TOKEN in .env (copy from DevTools on apollopharmacy.in)");
      return null;
    }

    const sessionId = randomUUID();
    const res = await fetch("https://apigateway.apollo247.in/search-service/v5/fullSearch", {
      method: "POST",
      headers: {
        "accept": "application/json, text/plain, */*",
        "accept-language": "en-US,en;q=0.8",
        "authorization": token,
        "content-type": "application/json",
        "x-app-os": "web",
        "x-device-id": DEVICE_ID,
        "x-source-service": "PHARMA_AP_IN",
        "x-token": "",
        "x-unique-session-id": sessionId,
        "Referer": "https://www.apollopharmacy.in/"
      },
      body: JSON.stringify({
        query: medicineName,
        page: 1,
        productsPerPage: 10,
        selSortBy: "relevance",
        filters: [],
        pincode: ""
      })
    });

    if (res.status === 401 || res.status === 403) {
      await redis.del(CACHE_KEY);
      console.warn("[Apollo] Token expired. Please refresh APOLLO_PUBLIC_TOKEN in .env");
      return null;
    }

    if (!res.ok) return null;

    const data = await res.json();
    const products = data?.data?.productDetails?.products;
    if (!products || products.length === 0) return null;

    // Pick first in-stock product
    const item = products.find(p => p.status === "in-stock") || products[0];
    if (!item) return null;

    const productName = item.name;
    const price = item.specialPrice != null ? `₹${item.specialPrice}` : item.price != null ? `₹${item.price}` : null;
    const productUrl = item.urlKey
      ? `https://www.apollopharmacy.in/dp/${item.urlKey}`
      : `https://www.apollopharmacy.in/search-medicines/${encodeURIComponent(medicineName)}`;

    return { vendor: "Apollo Pharmacy", productName, price, productUrl };
  } catch (err) {
    console.error("Apollo scrape failed:", err.message);
    return null;
  }
}
